---
# ─── Network ─────────────────────────────────────────────────
control_ip:  "192.168.56.10"
nginx_ip:    "192.168.56.11"
webserver_ip:  "192.168.56.12"
webserver2_ip: "192.168.56.13"
database_ip: "192.168.56.14"
monitor_ip:  "192.168.56.15"

# ─── Flask ───────────────────────────────────────────────────
flask_port: 5000
flask_user: vagrant